### ISSUE TITLE
sysconfig.cell does not exist

### ISSUE THREAD

**Issue by PennPanda** [siemens/jailhouse#15]
I'm using the master branch with the commit point 7ab5300aedc65b3dd1f9382bec9e5e23991db74b

After compiling the source successfully, I run the command as suggested in README: 

sudo ./tools/jailhouse hardware check sysconfig.cell

**It reports the following error:**

Traceback (most recent call last):
  File "./tools/jailhouse-hardware-check", line 153, in <module>
    config = Sysconfig(sys.argv[1])
  File "./tools/jailhouse-hardware-check", line 116, in __init__
    self.config = open(path, 'rb')
IOError: [Errno 2] No such file or directory: 'sysconfig.cell'

**Comment by jan-kiszka** [comment]
"sysconfig.cell" is meant as a place-holder for the system configuration of your host machine. You can generate this via jailhouse config create. We should probably clarify this in the README.

**Comment by jan-kiszka** [comment]
Actually, the required steps are already referenced in the readme.

**Comment by PennPanda** [comment]
Thank you very much for clarification! 
I didn't realize sysconfig.c is a placeholder instead of a concrete existing file. :-( 

So for each type of machine (for example, with different memories for), users have to figure out the devices on the machine and write their own sysconfig.c. Is my understanding correct?

I'm wondering if there is some documentation/tutorial about how to write such sysconfig.c? 

Is it better to run in QEMU if I, as an non-expert user, just want to try out Jailhouse first?

**Comment by jan-kiszka** [comment]
Let's do follow-up discussions on jailhouse-dev@googlegroups.com - that's more efficient because the target audience is larger.
