### ISSUE TITLE
Jailhouse dont compile in banana pi

### ISSUE THREAD

**Issue by inaciose** [siemens/jailhouse#18]
root@bananapi:~/src/osdev/src/jailhouse# make
  DTC     /root/src/osdev/src/jailhouse/configs/dts/inmate-amd-seattle.dtb
  DTC     /root/src/osdev/src/jailhouse/configs/dts/inmate-bananapi.dtb
/root/src/osdev/src/jailhouse/configs/dts/inmate-bananapi.dts:16:54: fatal error: dt-bindings/interrupt-controller/arm-gic.h: No such file or directory
 #include <dt-bindings/interrupt-controller/arm-gic.h>
                                                      ^
compilation terminated.
scripts/Makefile.lib:316: recipe for target '/root/src/osdev/src/jailhouse/configs/dts/inmate-bananapi.dtb' failed
make[4]: *** [/root/src/osdev/src/jailhouse/configs/dts/inmate-bananapi.dtb] Error 1
scripts/Makefile.build:553: recipe for target '/root/src/osdev/src/jailhouse/configs/dts' failed
make[3]: *** [/root/src/osdev/src/jailhouse/configs/dts] Error 2
scripts/Makefile.build:553: recipe for target '/root/src/osdev/src/jailhouse/configs' failed
make[2]: *** [/root/src/osdev/src/jailhouse/configs] Error 2
Makefile:1492: recipe for target '_module_/root/src/osdev/src/jailhouse' failed
make[1]: *** [_module_/root/src/osdev/src/jailhouse] Error 2
Makefile:36: recipe for target 'modules' failed
make: *** [modules] Error 2
root@bananapi:~/src/osdev/src/jailhouse#

**Comment by jan-kiszka** [comment]
Please report issues to the mailing list only. Make sure you also have studied https://github.com/siemens/jailhouse/blob/master/Documentation/setup-on-banana-pi-arm-board.md.
